limit_req_status 429;
limit_req_zone $binary_remote_addr zone=matrix_api:10m rate=20r/s;
log_format mk8_safe '$remote_addr - $remote_user [$time_local] '
                    '"$request_method $uri $server_protocol" $status $body_bytes_sent '
                    '$request_length $request_time "$http_user_agent"';
