server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    access_log /var/log/nginx/access.log mk8_safe;
    return 444;
}

server {
    listen 80;
    listen [::]:80;
    server_name email.mk8n.com mta-sts.mk8n.com autoconfig.mk8n.com;
    access_log /var/log/nginx/access.log mk8_safe;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 308 https://$host$request_uri;
    }
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;
    access_log /var/log/nginx/access.log mk8_safe;
    ssl_certificate /etc/mk8email/tls/fullchain.pem;
    ssl_certificate_key /etc/mk8email/tls/privkey.pem;
    ssl_reject_handshake on;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name email.mk8n.com;
    access_log /var/log/nginx/access.log mk8_safe;

    ssl_certificate /etc/mk8email/tls/fullchain.pem;
    ssl_certificate_key /etc/mk8email/tls/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_tickets off;
    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Content-Type-Options nosniff always;
    return 404;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name mta-sts.mk8n.com;
    access_log /var/log/nginx/access.log mk8_safe;

    ssl_certificate /etc/mk8email/tls/fullchain.pem;
    ssl_certificate_key /etc/mk8email/tls/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_tickets off;
    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Content-Type-Options nosniff always;

    location = /.well-known/mta-sts.txt {
        root /var/www/mta-sts;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 404;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name autoconfig.mk8n.com;
    access_log /var/log/nginx/access.log mk8_safe;

    ssl_certificate /etc/mk8email/tls/fullchain.pem;
    ssl_certificate_key /etc/mk8email/tls/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_tickets off;
    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Content-Type-Options nosniff always;

    location = /mail/config-v1.1.xml {
        root /var/www/autoconfig;
        default_type application/xml;
        try_files $uri =404;
    }

    location / {
        return 404;
    }
}
