z /etc/postgresql/17/main/postgresql.conf 0600 postgres postgres -
z /etc/postgresql/17/main/pg_ctl.conf 0600 postgres postgres -
z /etc/postgresql/17/main/start.conf 0600 postgres postgres -
z /etc/postgresql/17/main/pg_hba.conf 0640 postgres postgres -
