d /var/vmail 0750 vmail vmail -
d /var/lib/mk8email-admin 0750 mk8email mk8email -
d /var/lib/mk8email-admin/data-protection 0700 mk8email mk8email -
d /var/log/mk8email-admin 0750 mk8email mk8email -
d /var/lib/mk8-mail-health 2750 root mk8email -
