clamav {
  type = "clamav";
  symbol = "CLAM_VIRUS";
  servers = "/run/clamav/clamd.ctl";
  scan_mime_parts = true;
  scan_text_mime = true;
  scan_image_mime = true;
  log_clean = false;
  timeout = 30s;
  retransmits = 2;
  action = "reject";
  message = "The message contains prohibited or unsafe content";
}
