enabled = true;
sign_authenticated = true;
sign_local = false;
use_domain = "header";
allow_username_mismatch = false;
domain {
  mk8n.com {
    selector = "s202609";
    path = "/etc/mk8email/dkim/s202609.private.pem";
  }
}
