enabled = true;
sign_authenticated = true;
sign_local = false;
use_domain = "header";
use_esld = false;
allow_username_mismatch = false;
try_fallback = false;
selector_map = "/etc/rspamd/dkim_selectors.map";
path_map = "/etc/rspamd/dkim_paths.map";
