PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
PermitRootLogin prohibit-password
PermitEmptyPasswords no
MaxAuthTries 3
LoginGraceTime 30
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
DisableForwarding yes
PermitTunnel no
GatewayPorts no
PermitUserRC no
ClientAliveInterval 300
ClientAliveCountMax 2
TCPKeepAlive no
MaxSessions 2
MaxStartups 3:30:10
RequiredRSASize 3072
LogLevel VERBOSE
AuthenticationMethods publickey
AllowUsers root mkn8rn
