local   all         postgres                              peer
local   all         all                                   peer
host    mk8email    mk8email    127.0.0.1/32              scram-sha-256
host    mk8email    mk8email    ::1/128                   scram-sha-256
include_if_exists '/etc/postgresql/17/main/pg_hba.local.conf'
host    all         all         127.0.0.1/32              reject
host    all         all         ::1/128                   reject
