LocalSocket /run/clamav/clamd.ctl
FixStaleSocket true
LocalSocketGroup clamav
LocalSocketMode 660
User clamav
DatabaseDirectory /var/lib/clamav
OfficialDatabaseOnly true
Foreground true
ScanMail true
ScanArchive true
AlertEncryptedArchive true
AlertEncryptedDoc true
AlertExceedsMax true
ScanPE true
ScanOLE2 true
AlertOLE2Macros true
ScanPDF true
ScanHTML true
ScanSWF true
ScanELF true
ScanXMLDOCS true
ScanHWP3 true
PhishingSignatures true
PhishingScanURLs true
AlgorithmicDetection true
HeuristicScanPrecedence true
DetectPUA true
Bytecode true
BytecodeSecurity TrustSigned
ExtendedDetectionInfo true
FollowDirectorySymlinks false
FollowFileSymlinks false
CrossFilesystems false
LeaveTemporaryFiles false
ExitOnOOM true
MaxThreads 4
MaxConnectionQueueLength 20
MaxQueue 40
ReadTimeout 180
CommandReadTimeout 30
SendBufTimeout 200
IdleTimeout 30
MaxScanTime 120000
MaxScanSize 100M
MaxFileSize 25M
StreamMaxLength 26M
MaxRecursion 16
MaxDirectoryRecursion 15
MaxFiles 10000
PCREMatchLimit 10000
PCRERecMatchLimit 5000
PCREMaxFileSize 25M
SelfCheck 3600
LogSyslog false
LogRotate true
LogClean false
LogVerbose false
LogFile /var/log/clamav/clamav.log
LogTime true
LogFileMaxSize 10M
