DatabaseOwner clamav
DatabaseDirectory /var/lib/clamav
DatabaseMirror database.clamav.net
DNSDatabaseInfo current.cvd.clamav.net
Checks 24
MaxAttempts 5
ConnectTimeout 30
ReceiveTimeout 120
TestDatabases yes
ScriptedUpdates yes
Bytecode true
NotifyClamd /etc/clamav/clamd.conf
Foreground false
LogVerbose false
LogSyslog false
LogRotate true
LogTime true
UpdateLogFile /var/log/clamav/freshclam.log
LogFileMaxSize 5M
