bind 127.0.0.1 ::1
protected-mode yes
port 6379
tcp-backlog 128
timeout 0
tcp-keepalive 300
daemonize no
supervised systemd
pidfile /run/valkey/valkey-server.pid
loglevel notice
logfile ""
databases 4
always-show-logo no
set-proc-title yes
proc-title-template "{title} {listen-addr}"
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /var/lib/valkey
appendonly yes
appendfilename "appendonly.aof"
appenddirname "appendonlydir"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated no
aof-use-rdb-preamble yes
maxmemory 512mb
maxmemory-policy noeviction
rename-command FLUSHDB ""
rename-command FLUSHALL ""
