install dccp /bin/false
blacklist dccp
install firewire-core /bin/false
blacklist firewire-core
install firewire-sbp2 /bin/false
blacklist firewire-sbp2
install rds /bin/false
blacklist rds
install sctp /bin/false
blacklist sctp
install tipc /bin/false
blacklist tipc
